### ISSUE TITLE
Hooks documentration version 2.4.0

### ISSUE THREAD

**Issue by GitHK** [TurboGears/tg2#108]
The documentation for https://turbogears.readthedocs.io/en/latest/turbogears/hooks.html?highlight=hooks#available-hooks is out of date.

Instead of using `after_config` hook, which I was no longer able to find, I had to use `tg.milestones.config_ready`.

If this is correct, docs need fixing.

**Comment by amol-** [comment]
Thanks! I think I missed that during the doc update

**Comment by amol-** [comment]
Fixed in 4777a45
