### ISSUE TITLE
Error: tg.i18n.LanguageError: No translation file found for domain

### ISSUE THREAD

**Issue by hoang-rio** [TurboGears/tg2#110]
It work on local environment (MacOS, Windows) but it did not work in Server Centos 7 environment.
All of it use `gearbox serve` with Python 3.7.3 venv.
I sure that i have correct file in i18n folder

**Comment by amol-** [comment]
Were you able to find the reason for this?

**Comment by hoang-rio** [comment]
Becuase python find vi_VN folder for my language my folder name is vi_VN. And windows and mac os know it same but Linux not. I renamed it and it work again

Vào 8 Th8, 2019 18:39, Alessandro Molina <notifications@github.com> đã viết:

Were you able to find the reason for this?
