### ISSUE TITLE
Secure attribute for webflash cookie

### ISSUE THREAD

**Issue by kentontaylor** [TurboGears/tg2#120]
When any `webflash` cookie is set by TG, Firefox is now throwing the following warning in its console:

```
Cookie “webflash” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies
```

The relevant area in the source code seems to be within `TGFlash.__call__()`

**Comment by Mero89** [comment]
I Have the same problem, i configured flash messages to use toastr as described in the documentation.

**Comment by amol-** [comment]
Given the purpose of webflash cookie, it will probably retain the current functionalities if set to `SameSite=Strict` .

Will make a PR to test so.

**Comment by amol-** [comment]
https://github.com/TurboGears/tg2/commit/b0f6387a458e910482ddb87f8434eb8ff52f58d0 and https://github.com/TurboGears/tg2/commit/1956f4462d43f35993b7f786b7536a78d42f5c70 together should address the issue.
