### ISSUE TITLE
Improve the config system of TG2

### ISSUE THREAD

**Issue by pedersen** [TurboGears/tg2#13]
This issue existed in Trac. The original can be viewed at http://trac.turbogears.org/ticket/2240

This issue existed on SourceForge. The original can be viewed at https://sourceforge.net/p/turbogears2/tickets/72

**Comment by amol-** [comment]
Since 2.3.8 there is now guarantee that all options are properly read/write from conf currently being constructer nstead of mixing AppConfig/tg.config/currently under build conf

2.4.0 will aim at allowing to add/remove configuration steps while so far they have been hardcoded in AppConfig.
