### ISSUE TITLE
caching authentication requests

### ISSUE THREAD

**Issue by pedersen** [TurboGears/tg2#20]
This issue existed in Trac. The original can be viewed at cache,predicates,authentication

This issue existed on SourceForge. The original can be viewed at https://sourceforge.net/p/turbogears2/tickets/108

**Comment by amol-** [comment]
This has been tackled in documentation at https://github.com/TurboGears/tg2docs/commit/62140a3ad1da03cf4908e0a9e21935fd27eb3a29
