### ISSUE TITLE
add the toolbox back to turbogears 2?

### ISSUE THREAD

**Issue by pedersen** [TurboGears/tg2#4]
This issue existed in Trac. The original can be viewed at http://trac.turbogears.org/ticket/2164

This issue existed on SourceForge. The original can be viewed at https://sourceforge.net/p/turbogears2/tickets/59

**Comment by amol-** [comment]
This has been around for a few years and seems it is not much needed, didn't see users complaining nor I felt the need for it. Most of the tools are already available in tgext.admin or through Babel.

In case someone feels it's still needed feel free to reopen the ticket
