### ISSUE TITLE
Add http verb based predicates

### ISSUE THREAD

**Issue by pedersen** [TurboGears/tg2#5]
This issue existed in Trac. The original can be viewed at http://trac.turbogears.org/ticket/2231

This issue existed on SourceForge. The original can be viewed at https://sourceforge.net/p/turbogears2/tickets/60

**Comment by amol-** [comment]
It's not really clear to me what they should do.

Suppose you want to limit the access to only GET for some users that can be easily done using the ``@require`` decorator over a ``RestController``. So what should the verb predicates do?

**Comment by amol-** [comment]
Got no feedbacks on this, please re-open if still meaningful
