### ISSUE TITLE
An event stream or event resource with streaming response.

### ISSUE THREAD

**Issue by nesforge** [TurboGears/tg2#58]
Hello There,
I'm trying to make an event resource for javascript's EventSource object to fire flash messages on client side. But i've found that i'm actually unable to change any tg objects while streaming loop. 
The code:
```python
 @expose(content_type='text/event-stream')
 def events(self):

         def stream(): 
             while 1: 
                 yield bytearray(("data: %s::%s\n\n"%(
                     tg.flash.message, 
                     tg.flash.status
                 )).encode('utf-8')) 
                 time.sleep(3)

  return stream()
```
This code yields messages in format: "data: message::status". 

I dont know how tg works under the boonet, but as I understood the changes won't be applied unless the exposed method returns some response.
Currently i fetch flash messages by the means of frontend (i ping some resource after each succefull ajax requst).  

I also tried to get gevent-websocket working with tg, but i didn't see required changes in wsgi environ (wsgi.websocket object)
I see it's not so simple, but I hope you can give me rigiht dirrection to find an approach to this issue.

**Comment by nesforge** [comment]
Hi, 
I've solved this issuse by using custom flash function with independent storage. I tested it with the shelve module. I think it is able to work with redis or any storage. This approach would be usable to implement some kind of pub/subscribe. Thanks for reading.

The code:
```python
#custom flash message
from tg import request
import shelve

def flash(msg, status):
	name = request.identity['repoze.who.userid']
	s = shelve.open(name)
	s['message'] = "%s::%s"%(msg, status)
	s.close()

def get_flash():
	name = request.identity['repoze.who.userid']
	try:
		s = shelve.open(name)
		message = s['message']
		del s['message']
		s.close()
		return message
	except:
		return None
```

```python
    #event stream
    @expose(content_type='text/event-stream')
    def events(self):
            while 1: 
                msg = get_flash()
                if msg:
                    yield bytearray( ("data: %s\n\n"%msg).encode('utf-8')) 
                time.sleep(2)

```

**Comment by amol-** [comment]
Regarding websocket you might want to have a look at https://pypi.python.org/pypi/tgext.socketio which provides websocket and socket.io support.

Regarding the flash itself it works by storing and reading flash messages into a cookie, so it doesn't have much sense in the context of a streamed response as you will never receive the flash data. In that case you need to roll your own notification system. This is something you can also get for free using tgext.socketio pubsub support: https://pypi.python.org/pypi/tgext.socketio#pubsub-support
