### ISSUE TITLE
@cached decorator does not work as expexted

### ISSUE THREAD

**Issue by mouchar** [TurboGears/tg2#66]
Hi, I just tried to use ```@cached()``` decorator, as described in [docs](http://turbogears.readthedocs.org/en/latest/turbogears/caching.html?highlight=cache#controller-caching).
Unfortunately, it seems to be not working - it correctly stores the first value into cache, but subsequent calls return the cached version even when URL arguments change. I observed this behaviour only on ```_default()``` method. Here are steps to reproduce:

```python
import logging
from wsgiref.simple_server import make_server
from tg import expose, TGController, AppConfig, cached

logging.basicConfig(level=logging.DEBUG)

class RootController(TGController):
    @cached(expire=100)
    @expose()
    def index(self, **kw):
        return dict(status='works', **kw)

    @cached(expire=100)
    @expose()
    def _default(self, id):
        return dict(status='fails', id=id)


config = AppConfig(minimal=True, root_controller=RootController())
config['cache.enabled'] = True
config['default_renderer'] = 'json'

make_server('', 8080, config.make_wsgi_app()).serve_forever()
```

Let's try some tests:
```
# 1st index get, data stored to cache
$ curl http://localhost:8080/?id=1
{"status": "works", "id": "1"}
# 2nd index get with another parameter, data stored to cache
$ curl http://localhost:8080/?id=2
{"status": "works", "id": "2"}
# 1st get on _default, for id=3
$ curl http://localhost:8080/3
{"status": "fails", "id": "3"}
# 2nd get on _default with id=4, incorrectly returns cached value id=3
$ curl http://localhost:8080/4
{"status": "fails", "id": "3"}
```

I was not able to make ```@cached``` work using argument ```key```. It looks like cache key generating function is somehow broken.

**Comment by amol-** [comment]
cached itself is currently working as expected, as documented in http://turbogears.readthedocs.org/en/latest/reference/classes.html#tg.decorators.cached it currently only relies on the request parameters to generate the cache key. In your example both ``http://localhost:8080/3`` and ``http://localhost:8080/4`` have the same params (None) the only part that changed is the request PATH.

The fact that unhandled parts of the path are passed as argument to ``_default`` does not make them part of the parameters passed to the request. The arguments used to generate the cache key are those in ``request.args_params`` which are GET and POST parameters.

By the way I agree that function parameters and not request parameters should probably be used to create the cache key, but the change might have caused backward incompatibilities for past code and never got worked.

**Comment by mouchar** [comment]
OK, thanks for explanation, I really overlooked "request parameters" detail. However, this makes ```@cached``` useless for my use-case, as I wanted to cache responses from our REST interface that heavily use IDs as a part of the PATH_INFO.
I will use manual caching method instead.

**Comment by amol-** [comment]
https://github.com/TurboGears/tg2/commit/4aa60096bbf4beb70267e6319736bd44e9f26d69 and https://github.com/TurboGears/tg2/commit/e36a9db9f34c201439688de391227b137821349f now improved ``@cached`` behaviour and positional arguments are now considered when creating the cache_key. The test units have been updated to ensure that ``?arg=5`` and ``/5`` lead to the same cache key.

**Comment by mouchar** [comment]
Works like a charm! Thanks!
