### ISSUE TITLE
repoze.what is dead and depends on repoze.who <= 1.99 which is incompatible with pysaml2

### ISSUE THREAD

**Issue by SpamapS** [TurboGears/tg2#69]
pysaml2 requires repoze.who >=2.0. repoze.what cannot work with repoze.who v2 because of API breaking changes. repoze.what is dead, not receiving any commits for 5 years.

I'd suggest either

a) Adopting repoze.what, and updating it to work with new repoze.who
b) dropping repoze.what.

**Comment by SpamapS** [comment]
FYI, to relieve some analysis, this is the only place I could find that requires repoze.what (and it is just for the plugin):

https://github.com/TurboGears/tg2/blob/development/tg/configuration/app_config.py#L1042

Perhaps this could just be deprecated?

**Comment by moschlar** [comment]
The usage of repoze.what has not been advised for newly quickstarted projects for some time now:
http://turbogears.readthedocs.org/en/latest/cookbook/upgrading.html?highlight=upgrad#new-authentication-layer

See more in the new docs:
http://turbogears.readthedocs.org/en/latest/turbogears/authorization.html

**Comment by SpamapS** [comment]
Sweet, the Debian package still _depends_ on it, but it looks like we can drop that, which would mean we can drop python-repoze.what and python-repoze.what-plugins, which will free pysaml2 to migrate into testing. Huzzah! Thanks for the quick reply.

**Comment by amol-** [comment]
Uhm, sorry for being the late comer. 
Yep, repoze.what is only used when backward-compatibility authentication stack is enabled, it's not anymore used by nowadays. 

Actually I didn't think it was a blocking problem for pysaml2, when I needed use it with TG2 I quickly rolled out https://bitbucket.org/axant/tgapp-samlauth without relying on repoze.what at all.

**Comment by SpamapS** [comment]
FYI, the bug in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804809

**Comment by amol-** [comment]
Thanks, I greatly appreciate you noticing it. I always install TurboGears2 from pip, so I didn't even know there was a package in Debian :D

I'll close this as there is already the debian bug for tracking the issue, if debian people need anything feel freel to comment here or send an email to the ML.
