### ISSUE TITLE
TurboGears and IDE Support

### ISSUE THREAD

**Issue by ghost** [TurboGears/tg2#70]
Popular IDEs such as PyDev, Wing IDE and PyCharm explicit call out (on their websites) that they support frameworks such as Django, Flask, Pyramid and Web2Py.

It would be nice if TurboGears2 could work hand-in-hand with the most popular IDEs as well, so that TG2 could be referenced on their main pages as well.  I believe this type of visibility (and integration) would significantly help with obtaining contributors to TG2 as well as increasing the products user base.

Reference:
http://robertjliguori.blogspot.com/2015/11/python-ides-with-turbogears2-support.html

**Comment by italorossi** [comment]
In terms of working, it does work with PyCharm, I use it, even the debug, remote debug, and run works fine.

Since this issue is from 2015 maybe it can be closed. @amol- thoughts?

**Comment by amol-** [comment]
Works fine with PyCharm, but there are some minor issues (especially related to kajiki template) and there is no built-in support in PyCharm for running a turbogears app like there is for pyramid or django.
