### ISSUE TITLE
tw2 coexistence with tw1

### ISSUE THREAD

**Issue by alexbodn** [TurboGears/tg2#78]
in order for tw2 widgets to use the same resources with tw1 widgets on the same page, 
i have just submitted a [patch to tw2.core ](https://github.com/toscawidgets/tw2.core/issues/122).
in order for that to work, it is necessary to reverse the order of loading the tw1 and tw2 middlewares 
in tg.configuration.
please consider doing this.
alex

**Comment by amol-** [comment]
TW1 support was removed in 2.4
