### ISSUE TITLE
Multiple Databases needs Documentation fix

### ISSUE THREAD

**Issue by ali65** [TurboGears/tg2#83]
Latest 2.3.10 documentation at
http://turbogears.readthedocs.io/en/latest/cookbook/multiple-databases.html#id4
recommends to override the setup_sqlalchemy function of the AppConfig class, but the functions name was changed to _setup_sqlalchemy !

**Comment by mersilde** [comment]
Was just hit by this as well, the function signature also changed.

Comments in tg/configuration/app_config.py as need to be updated.

**Comment by amol-** [comment]
Should have been improved by https://github.com/TurboGears/tg2docs/commit/b7969f96a87eebdd6ad119c963e4a4faee2bea2c
