### ISSUE TITLE
Opening the redirected link in a new tab in HTTPFound()

### ISSUE THREAD

**Issue by eteamin** [TurboGears/tg2#87]
Is it a good idea to add `new_tab=True` to `tg.exceptions.HTTPFound()` as `HTTPFound('/', new_tab=True)` to be able to open the found link in a new tab in the browser?

**Comment by eteamin** [comment]
is this even possible?

**Comment by amol-** [comment]
I don't think there is any way to trigger this as HTTP Layer, it's something that can only be achieved through javascript/HTML `target`.
