### ISSUE TITLE
Feature request: Implementing background task management

### ISSUE THREAD

**Issue by eteamin** [TurboGears/tg2#95]
I came across https://pypi.python.org/pypi/django-background-tasks the other day and I was wondering that as far as I know tg lacks such feature. Would you accept any PR related to such feature? Because I'm willing to do so.

**Comment by amol-** [comment]
Look at https://pypi.python.org/pypi/TGScheduler/1.7.0 and  https://pypi.python.org/pypi/tgext.asyncjob I think those are what you are looking for. I also used Celery ( which provides both features ) with TG without major issues

**Comment by eteamin** [comment]
Thank you!
